### ISSUE TITLE
Feature Request: Remove a.out upon completion

### ISSUE THREAD

**Issue by Sanket-Mathur** [Bipul-Harsh/auto-cpp-compiler#1]
The executable target file generated (.\a.out) should be removed upon compilation as the default behavior of the application since it tends to change the git staging area if not careful to exclude it or add it in the .gitignore file.

**Comment by Bipul-Harsh** [comment]
Thanks for pointing it out, I will work on it soon

**Comment by Bipul-Harsh** [comment]
Hello @Sanket-Mathur, I have added the feature which you have asked regarding automatically deleting output file.

I am sharing link to the dev branc

https://github.com/Bipul-Harsh/auto-cpp-compiler/tree/dev

Please downlaod it, install and tell if it sorts out your problem.
