### ISSUE TITLE
Bug: Message prior to compilation when using powershell window embedded inside VSCode

### ISSUE THREAD

**Issue by Sanket-Mathur** [Bipul-Harsh/auto-cpp-compiler#2]
## Description
The editor is showing an error message upon compilation of the program using the acc command.
The compilation, however, works fine besides this message.

## To Reproduce
- Open the file in code and the embedded powershell window
- Change the editor of acc to code using
  ``` acc -ce code ```
- Compile the code using acc
  ``` acc filename.cpp ```

## Expected behavior
The code must be compiled and executed without any error messages unless something is wrong on the users end.

## Screenshots
Editor Configuration: Output of acc --se
![Editer Config](https://user-images.githubusercontent.com/52062536/140619764-0437d48f-96f4-456f-8ada-790b6da7753e.png)

Error Message: Output at compilation of the file
![Error Message](https://user-images.githubusercontent.com/52062536/140619789-5a0363c0-cfeb-4305-9749-2dd754ed1a7f.png)

## Desktop
 - OS: Windows 11
 - Editor: VSCode (version 1.62)
 - Version: 10.0.22000 Build 22000

**Comment by Bipul-Harsh** [comment]
@Sanket-Mathur Can you please also add the exact command which you run

**Comment by Sanket-Mathur** [comment]
```
acc '.\Rearrange a linked list.cpp'
```

**Comment by Bipul-Harsh** [comment]
@Sanket-Mathur I have performed the steps you put above but didn't get any errors like you mentioned.

The issue you mentioned is something with the vscode you are running.

I am attaching some links which I found in issues of vscode repositroy

https://github.com/microsoft/vscode/issues/115874
https://github.com/microsoft/vscode/issues/105191#issuecomment-690953187

Please let me know if above clarifies the reason for the error you are getting.

Till then I am closing this issue for now
